### ISSUE TITLE
didn't working

### ISSUE THREAD

**Issue by shafiktanbir** [sakil470004/devtools#2]
today i see when use your websites it didn't clearing the ** and it will be great if you add copy button on top right of the textarea..

here is this text that make problem  -------- 
 
""🌟 **Responsive Blog Layout Project Completed!** 🌟

Excited to share my latest project — a **clean, responsive blog layout** using **CSS Grid** for modern web design! 🖥️📱

💡 **Project Highlights:**
- Developed a blog section with **two-column layout** for desktop and **single-column layout** for mobile views.
- Implemented **responsive images** to ensure they scale perfectly across devices.
- Included **engaging content blocks** with "See More" buttons to encourage user interaction.
- Enhanced design with media queries to create a **seamless experience on all screen sizes**.

This project really pushed me to think about **user experience** and **accessibility** across multiple devices. I'm always excited to grow and learn in web development!

"

**Comment by Mynul-Sakil** [comment]
Hi I solved your problem . Please check after today It should be fixed
